title: [Bienvenido al sitio web!]
description: [Este es un ejemplo de una pagina web, para poder ir descubriendo como realizar una buena pagina.]

remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
